### ISSUE TITLE
No css file found on dist folder

### ISSUE THREAD

**Issue by juan-carvajal** [r3code/vue-vis-network#11]
The github page instructs to use the style in the dist folder, but there is no css file there. I builded and example and it was not showing properly.

**Comment by scenaristeur** [comment]
try import "vue-vis-network/node_modules/vis-network/dist/vis-network.css";

**Comment by r3code** [comment]
Use workaround by @scenaristeur  https://github.com/r3code/vue-vis-network/issues/8#issuecomment-685199075
Readme updated https://github.com/r3code/vue-vis-network/pull/17.
