### ISSUE TITLE
Infinite loop warning when using edges.smooth and layout.hierarchical together in options

### ISSUE THREAD

**Issue by tdong6** [r3code/vue-vis-network#14]
I am using vue-vis-network 1.0.2 and I see following warning in Chrome DevTools 
```
[Vue warn]: You may have an infinite update loop in watcher with expression "options"

found in

---> <Network> at src/components/Network.vue
       ...
```
when using the following options together
```
options: {
    ...
    layout: {
          hierarchical: {
            enabled: true,
            sortMethod: 'directed'
          }
    },
    ...
    edges: {
         ...
          smooth: {
            type: 'cubicBezier',
            forceDirection: 'horizontal',
            roundness: 0.5
          }
    }
}
```
The warning will disappear if I remove either of them. I don't find information on any restrictions using these two options. Any ideas?

**Comment by setaman** [comment]
this may be related to issue in vue2vis: https://github.com/alexcode/vue2vis/issues/53

**Comment by tdong6** [comment]
@setaman Thanks for the advice. 
I tried the workaround mentioned in the link but it doesn't resolve the issue for me.

**Comment by tdong6** [comment]
My bad, just realised my nodes and edges are `computed` properties. I defined options as a `computed` property other than `mounted` and it works for me. Thanks @setaman

**Comment by kelemenbalazs** [comment]
@tdong6 many thanks for your suggestion on Computed property. This saved my life now!!
