### ISSUE TITLE
Event code on the readme does not work

### ISSUE THREAD

**Issue by jeremynac** [r3code/vue-vis-network#20]
The code on the readme that demonstrates events calls the events: selectNode, hoverNode. I tried it and it does not work, it only works if I call them select-node and hover-node, like in the 'examples' folder.
Maybe I'm wrong but my guess is someone updated the library but forgot to update the readme.
I would be happy to do so.
It's a really nice project by the way, keep the good work!

**Comment by uier** [comment]
@jeremynac yeah, I think your guess is right.

The `Network` component emits the event whose name is the return value of `translateEvent(eventName)`.
https://github.com/r3code/vue-vis-network/blob/b10a14181fe8597e4b04370925058db595b186cc/src/components/Network.vue#L263-L267

and what `translateEvent` do is to turn the Camel Case event name into kebab Case.

https://github.com/r3code/vue-vis-network/blob/b10a14181fe8597e4b04370925058db595b186cc/src/utils.js#L35-L37

So it only works when we call them in kebab Case.

**Comment by Uier** [comment]
By the way, it seems that all Vis-network events are emitted by default in `Network` component.
So it's not necessary to passing the array if you wanna subscribe only Vis-network native events.
