### ISSUE TITLE
Wrong mapping for the  "on()", "off()" and "once()" methods of "network"

### ISSUE THREAD

**Issue by CamaradePopoff** [r3code/vue-vis-network#7]
In `Network.vue`, please correct the following method mappings (probably a bad copy-and-paste) for the `on()`, `off()` and `once()` methods.
Currently they are all mapped to the `moveTo()` method, which is a mistake:

```
on(event, callback) {
      this.network.moveTo(event, callback);
    },
    off(event, callback) {
      this.network.moveTo(event, callback);
    },
    once(event, callback) {
      this.network.moveTo(event, callback);
    },
```
should be:

```
on(event, callback) {
      this.network.on(event, callback);
    },
    off(event, callback) {
      this.network.off(event, callback);
    },
    once(event, callback) {
      this.network.once(event, callback);
    },
```

These methods are very useful, I have a project currently blocked because of this issue.
Please fix it!

Thank you in advance.

**Comment by r3code** [comment]
Please open a PR. I have no time right now to correct the issue.

**Comment by CamaradePopoff** [comment]
What kind of answer is that??

It's just **3 words** to change and the fix is done...

You have used 14 words to make the above answer, you could have saved 11 of them, which would have given you plenty of time to write the 3 we really need.
