### ISSUE TITLE
vueVisNetwork.css file missing in dist folder

### ISSUE THREAD

**Issue by CamaradePopoff** [r3code/vue-vis-network#8]
The README says:

> Add Visjs CSS
```
@import "vue-vis-network/dist/vueVisNetwork.css";
```

However, once `vue-vis-network` is npm-installed, the `node_modules\vue-vis-network\dist` folder does not contain the expected CSS file.

It is needed for proper display of the interaction and manipulation features of vis-network.

**Comment by and-jan** [comment]
In version 1.0.1 the file is not yet missing.

**Comment by CamaradePopoff** [comment]
Thanks for the info.
However, we need it to be there in the latest version of `vue-vis-network` you are proposing.
When could we have it fixed?
Thank you.

**Comment by r3code** [comment]
Thanks. I see it's missing in NPM. I'll try to fix ASAP.

**Comment by scenaristeur** [comment]
try import "vue-vis-network/node_modules/vis-network/dist/vis-network.css";

**Comment by r3code** [comment]
Use workaround by @scenaristeur  https://github.com/r3code/vue-vis-network/issues/8#issuecomment-685199075
Readme updated https://github.com/r3code/vue-vis-network/pull/17.
